---
- name: sample
  hosts: all
  tasks:
    - name: installing apache2
      yum:
          name: apache2
          state: latest
    - name: running apache2
      service: 
              name: apache2
              state: started
    - name: content
      copy:
           content: "hello akshay proxmox"
           dest: /var/www/html/index.html      
